- name: Creating link
  command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
  failed_when: false
  no_log: true
  when: ansible_distribution == "Ubuntu"


- name: Reloading firewall
  command: firewall-cmd --reload
  when: ansible_distribution == "Ubuntu"
